[package]
name = "roffl_gui"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"
description = "roffl graphical client"

[dependencies]
druid = { version = "*", path="../../druid/druid" }
docopt = "1.1.0"
keyring = "0.8.0"
clipboard = "0.5.0"
