[package]
name = "rcchat_proto"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"
description = "rcchat chat protocol"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
chrono = "0.4.11"
