name: clippy
on: [push, pull_request]
jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - name: Dependencies
      run: sudo apt-get install -y libgtk-3-dev libpango1.0-dev libcairo2-dev libcairo-gobject2
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -D warnings
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - name: Dependencies
      run: sudo apt-get install -y libgtk-3-dev libpango1.0-dev libcairo2-dev libcairo-gobject2
    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings
